name: Run Program on New Issue

on:
  issues:
    types:
      - opened

jobs:
  run_program:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run Program
      run: |
        # Hier den Befehl einfügen, um dein Programm mit dem Issue auszuführen
        echo "Running program for issue ${{ github.event.issue.number }}"
        python server.py
