name: Rust Compile

on:
  push:
    paths:
      - 'rust_project/**/*'

jobs:
  compile_rust:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        profile: minimal

    - name: Compile Rust Project
      run: |
        cd rust_project
        cargo build --release
